services:
  frontend:
    build:
      context: .
      args:
        NG_APP_API_URL: ${NG_APP_API_URL}
        MY_ENV: ${MY_ENV}
      dockerfile: Dockerfile
    image: rve-frontend
    ports:
      - '8000:8000'
